[book]
authors = ["cascades-sjtu"]
language = "en"
multilingual = false
src = "src"
title = "NIS7021 Lab Documentation"

[output.html]
git-repository-url = "https://github.com/cascades-sjtu/nis7021-labs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/cascades-sjtu/nis7021-labs/issues/new/choose"
site-url = "https://cascades-sjtu.github.io/nis7021-labs/"

[output.pdf]
optional = true
display-header-footer = true
static_site_url = "https://cascades-sjtu.github.io/nis7021-labs/"
header-template = "<h3 style='font-size:10px; margin-left: 40%' class='title'></h3>"
footer-template = "<p style='font-size:10px; margin-left: 48%'><span class='pageNumber'></span> / <span class='totalPages'></span></p>"